-- AI-Powered Credit Risk Intelligence Platform Schema
-- Target Database: SQLite

-- 1. Main Applications Table
CREATE TABLE IF NOT EXISTS applications (
    SK_ID_CURR INTEGER PRIMARY KEY,
    TARGET INTEGER DEFAULT 0, -- 1 = Default (Late payment), 0 = Repaid
    NAME_CONTRACT_TYPE TEXT CHECK(NAME_CONTRACT_TYPE IN ('Cash loans', 'Revolving loans')),
    CODE_GENDER TEXT CHECK(CODE_GENDER IN ('M', 'F', 'XNA')),
    FLAG_OWN_CAR TEXT CHECK(FLAG_OWN_CAR IN ('Y', 'N')),
    FLAG_OWN_REALTY TEXT CHECK(FLAG_OWN_REALTY IN ('Y', 'N')),
    CNT_CHILDREN INTEGER DEFAULT 0,
    AMT_INCOME_TOTAL REAL NOT NULL,
    AMT_CREDIT REAL NOT NULL,
    AMT_ANNUITY REAL,
    AMT_GOODS_PRICE REAL,
    NAME_INCOME_TYPE TEXT,
    NAME_EDUCATION_TYPE TEXT,
    NAME_FAMILY_STATUS TEXT,
    NAME_HOUSING_TYPE TEXT,
    DAYS_BIRTHDAY INTEGER, -- Age in days (negative value)
    DAYS_EMPLOYED INTEGER, -- Employment duration in days (negative value)
    OCCUPATION_TYPE TEXT,
    CNT_FAM_MEMBERS INTEGER DEFAULT 1,
    REGION_RATING_CLIENT INTEGER, -- 1, 2, 3
    EXT_SOURCE_1 REAL, -- Normalized external score 1
    EXT_SOURCE_2 REAL, -- Normalized external score 2
    EXT_SOURCE_3 REAL  -- Normalized external score 3
);

-- Index on target for analytics speed
CREATE INDEX IF NOT EXISTS idx_applications_target ON applications(TARGET);
CREATE INDEX IF NOT EXISTS idx_applications_income ON applications(NAME_INCOME_TYPE);

-- 2. Credit Bureau Table (Credits from other financial institutions)
CREATE TABLE IF NOT EXISTS bureau (
    SK_ID_BUREAU INTEGER PRIMARY KEY,
    SK_ID_CURR INTEGER,
    CREDIT_ACTIVE TEXT CHECK(CREDIT_ACTIVE IN ('Closed', 'Active', 'Sold', 'Bad debt')),
    CREDIT_CURRENCY TEXT,
    DAYS_CREDIT INTEGER, -- How many days ago did the client apply for Bureau credit
    CREDIT_DAY_OVERDUE INTEGER DEFAULT 0,
    DAYS_CREDIT_ENDDATE INTEGER,
    DAYS_ENDDATE_FACT INTEGER,
    AMT_CREDIT_MAX_OVERDUE REAL,
    CNT_CREDIT_PROLONG INTEGER DEFAULT 0,
    AMT_CREDIT_SUM REAL,
    AMT_CREDIT_SUM_DEBT REAL,
    AMT_CREDIT_SUM_LIMIT REAL,
    AMT_CREDIT_SUM_OVERDUE REAL,
    CREDIT_TYPE TEXT,
    DAYS_CREDIT_UPDATE INTEGER,
    FOREIGN KEY(SK_ID_CURR) REFERENCES applications(SK_ID_CURR)
);

CREATE INDEX IF NOT EXISTS idx_bureau_curr ON bureau(SK_ID_CURR);

-- 3. Previous Home Credit Applications
CREATE TABLE IF NOT EXISTS previous_applications (
    SK_ID_PREV INTEGER PRIMARY KEY,
    SK_ID_CURR INTEGER,
    NAME_CONTRACT_TYPE TEXT,
    AMT_ANNUITY REAL,
    AMT_APPLICATION REAL,
    AMT_CREDIT REAL,
    AMT_DOWN_PAYMENT REAL,
    AMT_GOODS_PRICE REAL,
    WEEKDAY_APPR_PROCESS_START TEXT,
    HOUR_APPR_PROCESS_START INTEGER,
    FLAG_LAST_APPL_PER_CONTRACT TEXT,
    NFLAG_LAST_APPL_IN_DAY INTEGER,
    RATE_DOWN_PAYMENT REAL,
    RATE_INTEREST_PRIMARY REAL,
    RATE_INTEREST_PRIVILEGED REAL,
    NAME_CASH_PORTFOLIO_LIMIT_EXP TEXT,
    NAME_CONTRACT_STATUS TEXT CHECK(NAME_CONTRACT_STATUS IN ('Approved', 'Refused', 'Canceled', 'Unused offer')),
    DAYS_DECISION INTEGER,
    NAME_PAYMENT_TYPE TEXT,
    CODE_REJECT_REASON TEXT,
    FOREIGN KEY(SK_ID_CURR) REFERENCES applications(SK_ID_CURR)
);

CREATE INDEX IF NOT EXISTS idx_prev_curr ON previous_applications(SK_ID_CURR);
